// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfM6CuCywXESPL1Mt0bmA29WLTIxoaoo',
    appId: '1:504276280125:web:e84852c5fc91a010ed9b54',
    messagingSenderId: '504276280125',
    projectId: 'doctorapp-b57fb',
    authDomain: 'doctorapp-b57fb.firebaseapp.com',
    storageBucket: 'doctorapp-b57fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Of1vTt0AHPZNsY4XNL9DJt7kmB3zyao',
    appId: '1:504276280125:android:1f8c876b9c9917e0ed9b54',
    messagingSenderId: '504276280125',
    projectId: 'doctorapp-b57fb',
    storageBucket: 'doctorapp-b57fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClDwpmduM2KbNWHvUYgYV9z6791pHwf6c',
    appId: '1:504276280125:ios:2443ea8dfe800178ed9b54',
    messagingSenderId: '504276280125',
    projectId: 'doctorapp-b57fb',
    storageBucket: 'doctorapp-b57fb.appspot.com',
    iosClientId: '504276280125-602a7m7ipoe015m7j178buh8b06m0tpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClDwpmduM2KbNWHvUYgYV9z6791pHwf6c',
    appId: '1:504276280125:ios:2443ea8dfe800178ed9b54',
    messagingSenderId: '504276280125',
    projectId: 'doctorapp-b57fb',
    storageBucket: 'doctorapp-b57fb.appspot.com',
    iosClientId: '504276280125-602a7m7ipoe015m7j178buh8b06m0tpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorapp',
  );
}
